ahmet = """2010 YILINDA MODERN BİR CAFE-RESTAURANT-BAR OLARAK AÇILAN “SOSTA” DÜNYA MUTFAĞI HAFTANIN 4 GÜNÜ EŞSİZ CANLI MÜZİK SERVİSİ VE EĞLENCELİ ORTAMI İLE KISA SÜREDE AVRUPA YAKASININ EN ÇOK KONUŞULAN YERLERİNDEN BİRİ OLMUŞTUR HERKESİN BULUŞMA NOKTASI OLAN “SOSTA” ÖZELLİKLE HAFTA SONLARI GECELERİ ÇOK HAREKETLENEN "SOSTA" MÜŞTERİLERİNE ÖZENLE EV SAHİPLİĞİ YAPMAKTADIR.

ALKOLLÜ ALKOLSÜZ SICAK SOĞUK BÜTÜN ARADIKLARINIZI BULABİLECEĞİNİZ MEKANIMIZ GÜNDÜZLERİ SAKİNLİĞİ YAKALAYABİLCEĞİNİZ AKŞAMLARI BÜTÜN STRESİNİZİ ATABİLCEĞİNİZ EŞSİZ BİR MEKAN. HUZURLU KEYİFLİ BİR ATMOSFERDE VAKİT GEÇİRMEK İSTEYENLERİN MUDAVİMİ HALİNE GELDİĞİ "SOSTA" FARKLI BİR SOLUK GETİRDİĞİ HİZMET ANLAYIŞI İLE SOHBETLERİNİZİ DÜŞÜNEREK SEÇTİĞİ KALİTELİ VE NEŞELİ ÖZELLİKLERLE SÜSLEYEREK ZAMANINIZI DOLU DOLU YAŞAMAYA DEVAM EDİYOR.

GÜLERYÜZLÜ İNSANLARLA KARŞILAŞACAĞINIZ BU SICAK CAFE DE ATIŞTIRMALIK BİR ŞEYLER YEMEK-İÇMEK ARKADAŞLARLA SOHBET ETMEK KEYİFLİ BİR ORTAMDA BULUNMAK EN GÜZEL BULUŞMALAR YAŞAMANIZ VE EN UNUTULMAZ ANILARI BİRİKTİRMENİZ İÇİN SİZLERİ RESTAURANTIMIZA BEKLİYORUZ.""".lower()

print ahmet
